server:
    port: 8080
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/franherran
        username: franherran
        password: 1234
    jpa:
        hibernate:
            ddl-auto: update
jwt:
    secret: lkhfiusdfoyuqu9weifjuredshgfhwejkyfhgieywsdjfegrydisuifhhewyousgdfyiwejhksdfghweacdgyujtrhgdfjgjkjdjtfjghfd
springdoc:
    api-docs:
        path: /v1/api-docs
    swagger-ui:
        path: /swagger-ui/index.html